//
// Created by Shiki on 2021/4/6.
//

#ifndef NATIVEOPENGLLEARN_DEMO_INCLUDE_CONSTANTS_H_
#define NATIVEOPENGLLEARN_DEMO_INCLUDE_CONSTANTS_H_
const int CODE_ERROR = -1;
const int CODE_SUCCESS = 0;
#endif //NATIVEOPENGLLEARN_DEMO_INCLUDE_CONSTANTS_H_
